apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-monedas-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-monedas
  template:
    metadata:
      labels:
        app: api-monedas
    spec:
      containers:
      - name: api-monedas
        image: api-monedas:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/monedas
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: JWT_SECRET
          value: mySecretKey123456789
        - name: JWT_EXPIRATION
          value: "86400000"
---
apiVersion: v1
kind: Service
metadata:
  name: api-monedas-service
  namespace: default
spec:
  selector:
    app: api-monedas
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer