apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # postgres:sa (base64 encoded)
  postgres-password: c2E=
  postgres-user: cG9zdGdyZXM=
  postgres-db: bW9uZWRhcw==