apiVersion: v1
kind: ConfigMap
metadata:
  name: api-monedas-config
  namespace: apimonedas
data:
  # Configuración de la aplicación
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  
  # Configuración de JPA
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  
  # Configuración de logs
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "INFO"
  LOGGING_LEVEL_ORG_HIBERNATE_SQL: "INFO"
  LOGGING_LEVEL_ROOT: "INFO"
  
  # Configuración de base de datos
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/monedas"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
